"""Initial migration

Revision ID: 9113653482ea
Revises: 
Create Date: 2026-01-27 20:10:54.353717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9113653482ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_email', 'otps', ['email'], unique=False)
    op.create_index('idx_otp_email_purpose', 'otps', ['email', 'purpose'], unique=False)
    op.create_index('idx_otp_expires_at', 'otps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('ix_otps_expires_at'), 'otps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_id', 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_income', sa.Integer(), nullable=False),
    sa.Column('total_expense', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_date')
    )
    op.create_index('idx_balance_date', 'balance_history', ['date'], unique=False)
    op.create_index('idx_balance_user_date', 'balance_history', ['user_id', 'date'], unique=False)
    op.create_index('idx_balance_user_id', 'balance_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_balance_history_date'), 'balance_history', ['date'], unique=False)
    op.create_index(op.f('ix_balance_history_id'), 'balance_history', ['id'], unique=False)
    op.create_index(op.f('ix_balance_history_user_id'), 'balance_history', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budget_user_id', 'budgets', ['user_id'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lender', sa.String(length=255), nullable=False),
    sa.Column('principal_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_principal', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('repayment_frequency', sa.String(length=50), nullable=False),
    sa.Column('emi', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('is_paid_off', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loan_next_due_date', 'loans', ['next_due_date'], unique=False)
    op.create_index('idx_loan_user_id', 'loans', ['user_id'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_next_due_date'), 'loans', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    op.create_table('saving_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_saving_goal_target_date', 'saving_goals', ['target_date'], unique=False)
    op.create_index('idx_saving_goal_user_id', 'saving_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_saving_goals_id'), 'saving_goals', ['id'], unique=False)
    op.create_index(op.f('ix_saving_goals_target_date'), 'saving_goals', ['target_date'], unique=False)
    op.create_index(op.f('ix_saving_goals_user_id'), 'saving_goals', ['user_id'], unique=False)
    op.create_table('shopping_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'SHOPPING', 'POST_SHOPPING', 'COMPLETED', name='shoppingplanstatus'), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shopping_plan_date', 'shopping_plans', ['plan_date'], unique=False)
    op.create_index('idx_shopping_plan_status', 'shopping_plans', ['status'], unique=False)
    op.create_index('idx_shopping_plan_user_id', 'shopping_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_shopping_plans_id'), 'shopping_plans', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_plans_plan_date'), 'shopping_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_shopping_plans_user_id'), 'shopping_plans', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_category', sa.String(length=100), nullable=True),
    sa.Column('ai_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('usage_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_user_tag_name')
    )
    op.create_index('idx_tag_name', 'tags', ['name'], unique=False)
    op.create_index('idx_tag_user_id', 'tags', ['user_id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expense_budget_id', 'expenses', ['budget_id'], unique=False)
    op.create_index('idx_expense_date', 'expenses', ['date'], unique=False)
    op.create_index('idx_expense_tag_id', 'expenses', ['tag_id'], unique=False)
    op.create_index('idx_expense_user_date', 'expenses', ['user_id', 'date'], unique=False)
    op.create_index('idx_expense_user_id', 'expenses', ['user_id'], unique=False)
    op.create_index(op.f('ix_expenses_budget_id'), 'expenses', ['budget_id'], unique=False)
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_tag_id'), 'expenses', ['tag_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('SALARY', 'RENTAL', 'INVESTMENTS', 'FREELANCE', 'GIFTS', 'OTHER', name='incomecategory'), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_income_category', 'incomes', ['category'], unique=False)
    op.create_index('idx_income_date', 'incomes', ['date'], unique=False)
    op.create_index('idx_income_tag_id', 'incomes', ['tag_id'], unique=False)
    op.create_index('idx_income_user_date', 'incomes', ['user_id', 'date'], unique=False)
    op.create_index('idx_income_user_id', 'incomes', ['user_id'], unique=False)
    op.create_index(op.f('ix_incomes_date'), 'incomes', ['date'], unique=False)
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.create_index(op.f('ix_incomes_tag_id'), 'incomes', ['tag_id'], unique=False)
    op.create_index(op.f('ix_incomes_user_id'), 'incomes', ['user_id'], unique=False)
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('need_want', sa.Enum('NEED', 'WANT', name='needwant'), nullable=False),
    sa.Column('estimate_price', sa.Integer(), nullable=False),
    sa.Column('actual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('is_moved_to_next', sa.Boolean(), nullable=False),
    sa.Column('is_out_of_plan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['shopping_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shopping_item_plan_id', 'shopping_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_shopping_items_id'), 'shopping_items', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_items_plan_id'), 'shopping_items', ['plan_id'], unique=False)
    op.create_table('loan_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Integer(), nullable=False),
    sa.Column('interest_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_repayment_loan_id', 'loan_repayments', ['loan_id'], unique=False)
    op.create_index('idx_repayment_scheduled_date', 'loan_repayments', ['scheduled_date'], unique=False)
    op.create_index('idx_repayment_status', 'loan_repayments', ['status'], unique=False)
    op.create_index('idx_repayment_user_id', 'loan_repayments', ['user_id'], unique=False)
    op.create_index(op.f('ix_loan_repayments_id'), 'loan_repayments', ['id'], unique=False)
    op.create_index(op.f('ix_loan_repayments_loan_id'), 'loan_repayments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_repayments_scheduled_date'), 'loan_repayments', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_loan_repayments_user_id'), 'loan_repayments', ['user_id'], unique=False)
    op.create_table('saving_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['saving_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contribution_date', 'saving_contributions', ['date'], unique=False)
    op.create_index('idx_contribution_goal_id', 'saving_contributions', ['goal_id'], unique=False)
    op.create_index('idx_contribution_user_id', 'saving_contributions', ['user_id'], unique=False)
    op.create_index(op.f('ix_saving_contributions_date'), 'saving_contributions', ['date'], unique=False)
    op.create_index(op.f('ix_saving_contributions_goal_id'), 'saving_contributions', ['goal_id'], unique=False)
    op.create_index(op.f('ix_saving_contributions_id'), 'saving_contributions', ['id'], unique=False)
    op.create_index(op.f('ix_saving_contributions_user_id'), 'saving_contributions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saving_contributions_user_id'), table_name='saving_contributions')
    op.drop_index(op.f('ix_saving_contributions_id'), table_name='saving_contributions')
    op.drop_index(op.f('ix_saving_contributions_goal_id'), table_name='saving_contributions')
    op.drop_index(op.f('ix_saving_contributions_date'), table_name='saving_contributions')
    op.drop_index('idx_contribution_user_id', table_name='saving_contributions')
    op.drop_index('idx_contribution_goal_id', table_name='saving_contributions')
    op.drop_index('idx_contribution_date', table_name='saving_contributions')
    op.drop_table('saving_contributions')
    op.drop_index(op.f('ix_loan_repayments_user_id'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_scheduled_date'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_loan_id'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_id'), table_name='loan_repayments')
    op.drop_index('idx_repayment_user_id', table_name='loan_repayments')
    op.drop_index('idx_repayment_status', table_name='loan_repayments')
    op.drop_index('idx_repayment_scheduled_date', table_name='loan_repayments')
    op.drop_index('idx_repayment_loan_id', table_name='loan_repayments')
    op.drop_table('loan_repayments')
    op.drop_index(op.f('ix_shopping_items_plan_id'), table_name='shopping_items')
    op.drop_index(op.f('ix_shopping_items_id'), table_name='shopping_items')
    op.drop_index('idx_shopping_item_plan_id', table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_incomes_user_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_tag_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_date'), table_name='incomes')
    op.drop_index('idx_income_user_id', table_name='incomes')
    op.drop_index('idx_income_user_date', table_name='incomes')
    op.drop_index('idx_income_tag_id', table_name='incomes')
    op.drop_index('idx_income_date', table_name='incomes')
    op.drop_index('idx_income_category', table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_tag_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_budget_id'), table_name='expenses')
    op.drop_index('idx_expense_user_id', table_name='expenses')
    op.drop_index('idx_expense_user_date', table_name='expenses')
    op.drop_index('idx_expense_tag_id', table_name='expenses')
    op.drop_index('idx_expense_date', table_name='expenses')
    op.drop_index('idx_expense_budget_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('idx_tag_user_id', table_name='tags')
    op.drop_index('idx_tag_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_shopping_plans_user_id'), table_name='shopping_plans')
    op.drop_index(op.f('ix_shopping_plans_plan_date'), table_name='shopping_plans')
    op.drop_index(op.f('ix_shopping_plans_id'), table_name='shopping_plans')
    op.drop_index('idx_shopping_plan_user_id', table_name='shopping_plans')
    op.drop_index('idx_shopping_plan_status', table_name='shopping_plans')
    op.drop_index('idx_shopping_plan_date', table_name='shopping_plans')
    op.drop_table('shopping_plans')
    op.drop_index(op.f('ix_saving_goals_user_id'), table_name='saving_goals')
    op.drop_index(op.f('ix_saving_goals_target_date'), table_name='saving_goals')
    op.drop_index(op.f('ix_saving_goals_id'), table_name='saving_goals')
    op.drop_index('idx_saving_goal_user_id', table_name='saving_goals')
    op.drop_index('idx_saving_goal_target_date', table_name='saving_goals')
    op.drop_table('saving_goals')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_next_due_date'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index('idx_loan_user_id', table_name='loans')
    op.drop_index('idx_loan_next_due_date', table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index('idx_budget_user_id', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_balance_history_user_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_date'), table_name='balance_history')
    op.drop_index('idx_balance_user_id', table_name='balance_history')
    op.drop_index('idx_balance_user_date', table_name='balance_history')
    op.drop_index('idx_balance_date', table_name='balance_history')
    op.drop_table('balance_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_id', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_expires_at'), table_name='otps')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_index('idx_otp_expires_at', table_name='otps')
    op.drop_index('idx_otp_email_purpose', table_name='otps')
    op.drop_index('idx_otp_email', table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
